---

- block:
  - name: create required .vim and Plug directories
    file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
    with_items:
      - "/home/{{ansible_env.SUDO_USER}}/.vim"
      - "/home/{{ansible_env.SUDO_USER}}/.vim/autoload"
      - "/home/{{ansible_env.SUDO_USER}}/.vim/plugged"
      - "/home/{{ansible_env.SUDO_USER}}/.ansible/tmp"

  - name: get Plug vim plugin manager
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: "/home/{{ansible_env.SUDO_USER}}/.vim/autoload/plug.vim"
      mode: '0640'

  - name: installing new .vimrc with Plug support - any existing .vimrc file will be backed up
    template:
      src: templates/dot.vimrc.template
      dest: "/home/{{ ansible_env.SUDO_USER }}/.vimrc"
      mode: '0640'
      backup: yes
    tags:
    - config
  
  - name: install tidal-vim plugin
    shell: vim.nox +Silent +VimEnter +PlugInstall +qall

  become: yes
  become_method: su
  become_user: "{{ansible_env.SUDO_USER}}"
  become_flags: '-s /bin/bash'

- name: set up tidal symlink in the PATH
  file:
    src: "/home/{{ansible_env.SUDO_USER}}/.vim/plugged/vim-tidal/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  with_items:
    - tidal
    - tidalvim

- include_role:
    name: "roles/ugens-{{ item }}"
  vars:
    editor: "{{ vim.editor }}"
  with_items: "{{ sc_ugens }}"
  when: sc_ugens is defined
